CREATE TABLE CHANGE_PROGRAM_QUEUE
(
    id                 BIGINT AUTO_INCREMENT,
    ROAD_CONTROLLER_ID BIGINT    NOT NULL,
    NEW_PROGRAM_ID     BIGINT    NOT NULL,
    CHANGE_TIME        TIMESTAMP NOT NULL
);
